CREATE TABLE animal
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_animal        VARCHAR(50) NOT NULL ,
    nome_provisorio   VARCHAR(100)                            NOT NULL,
    idade_estimada    INT                                     NOT NULL,
    raca              VARCHAR(100)                            NOT NULL,
    data_entrada      TIMESTAMP                               NOT NULL,
    data_adocao       TIMESTAMP,
    condicoes_chegada VARCHAR(255)                            NOT NULL,
    nome_recebedor    VARCHAR(100)                            NOT NULL,
    data_obito        TIMESTAMP,
    porte             VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);